#! /bin/bash
read -r -p "Are you sure? [Y/n] " response
if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]
then
	echo " "
	echo " "
	echo "----------------------------------------------------"
	echo "We are going LIVE!!!!!!!! WOOOOOOT";
	echo "----------------------------------------------------"
	echo " "
	echo " "
	rsync -avH --delete --exclude=.idea --exclude=.htaccess --exclude=favicon.ico --exclude=atomi/start.php --exclude=logs --exclude=assets/.sass-cache ~/PhpstormProjects/ellenbutters/. root@wizardlogic.com:/var/www/html/eb/
else
	exit
fi